### PR TITLE
Use nvim-web-devicons for statusline file icons

### PR DESCRIPTION
**Pull request by psynyde**

### CODE REVIEW

**Comment by psynyde** [comment]
use `%f` on `statusline.lua#L59` if you want file name with directory like before, but just the name seems cleaner than full path

**Comment by Manas140** [comment]
It does look good not to show the full name, yet adding a new plugin for what's already present isn't what I'd prefer.

**Comment by psynyde** [comment]
> It does look good not to show the full name, yet adding a new plugin for what's already present isn't what I'd prefer.

hm interesting, i didn't notice you don't have `nvim-web-devicons` as dependency for `nvim-tree`.
i know it's optional but I've seen almost everyone including that. I'd suggest to add it cause many plugins use it and also doesn't add a lot to the stack

**Comment by Manas140** [comment]
This is opinionated, but I prefer not to have those icons, now that I've tried it, as all it makes the nvim-tree is cluttered for some extra two chars.

Thanks for the contribution yet I don't see adding the web-dev-icons plugin as useful

**Pull request closed without merging**
